#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  16000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_I2S_METHOD_SIMPLEX

#ifdef AUDIO_I2S_METHOD_SIMPLEX
// 麦克风 I2S：麦SD接到ESP GPIO19
#define AUDIO_I2S_MIC_GPIO_WS   GPIO_NUM_22
#define AUDIO_I2S_MIC_GPIO_SCK  GPIO_NUM_21
#define AUDIO_I2S_MIC_GPIO_DIN  GPIO_NUM_19

// 功放 I2S：ESP GPIO25输出 → 功放DIN
#define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_25
#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_26
#define AUDIO_I2S_SPK_GPIO_LRCK GPIO_NUM_27
#else
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_26
#define AUDIO_I2S_GPIO_LRCK GPIO_NUM_27
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_19
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_25
#endif

// ========== 按键核心修改：长按按住录音，松开立即停止 ==========
#define BOOT_BUTTON_GPIO        GPIO_NUM_5
#define BOOT_BUTTON_ACTIVE_LEVEL 0
// 关键：BUTTON_MODE_HOLD 按住开启，松开结束；BUTTON_MODE_CLICK是单击触发
#define BOOT_BUTTON_MODE BUTTON_MODE_HOLD

// LED
#define LED_GPIO_PIN            GPIO_NUM_4
#define LED_ACTIVE_LEVEL        1

// 关闭唤醒词，保留网页配网
#define CONFIG_USE_WAKE_WORD    false
#define CONFIG_WAKE_WORD_ENGINE "none"
#define CONFIG_WEB_PROVISION_ENABLE true

#endif // _BOARD_CONFIG_H_
